### PR TITLE
Add UnsupportedOperationExc to host interface

### PR DESCRIPTION
**Pull request by flaiker**

### CODE REVIEW

**Comment by larshp** [comment]
I'll take a look at abaplint, at least `Expected ENDIF` looks like a false positive

**Comment by flaiker** [comment]
Thanks, made me notice the path in package.json ignored a lot of files...

Is there a way to ignore the generated table maintenance code in abaplint?

**Comment by larshp** [comment]
abaplint 1.5.9 released, update abaplint.json with `"skipGeneratedFunctionGroups": true`

**Comment by flaiker** [comment]
Thanks! I'll take a look at the other messages in a different PR.

**Comment by larshp** [comment]
cool, finding a lot of bugs in abaplint.org :)

**Comment by flaiker** [comment]
Happy to help :D

**Pull request merged**
