### PR TITLE
Fix formatting

### PR DESCRIPTION
**Pull request by flaiker**

### CODE REVIEW

**Comment by larshp** [comment]
request rerun of the check under https://github.com/flaiker/ci-lib/pull/7/checks

I've changed the code to lint all under src/**/*.* instead of only *.abap

**Comment by flaiker** [comment]
Did that work? The check is green now but the error messages seem to still be there.

**Comment by larshp** [comment]
hmm, yea, *shrug*, the Checks API is quite buggy and limited IMHO

**Comment by flaiker** [comment]
Well, let's see. Running into the same situation again might be quite rare.

**Pull request merged**
